/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogodavelha;

import org.jpl7.*;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comecarX(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(218, 216, 216));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever0(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever1(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever3(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever5(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever6(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever7(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton9.setToolTipText("");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever8(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever2(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escrever4(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("JOGO DA VELHA");

        jLabel2.setText("Jogador - X");

        jLabel3.setText("Computador - O");

        jButton10.setBackground(new java.awt.Color(255, 51, 51));
        jButton10.setText("Terminar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminar(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(102, 255, 102));
        jButton11.setText("Reiniciar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reiniciar(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 51));
        jButton12.setText("Computador começar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bolaComecar(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 51));
        jButton13.setText("Jogador começar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xComecar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void escrever0(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever0
        // TODO add your handling code here:
       // jButton1.setEnabled(false);
         jButton1.setText("X");
         tabuleiro[0] ='X';
         this.jogar();
    }//GEN-LAST:event_escrever0

    private void escrever1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever1
        // TODO add your handling code here:
        // jButton2.setEnabled(false);
         jButton2.setText("X");
          tabuleiro[1] ='X';
          this.jogar();
    }//GEN-LAST:event_escrever1

    private void escrever2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever2
        // TODO add your handling code here:
        // jButton3.setEnabled(false);
         jButton3.setText("X");
          tabuleiro[2] ='X';
          this.jogar();
    }//GEN-LAST:event_escrever2

    private void escrever3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever3
        // TODO add your handling code here:
        // jButton4.setEnabled(false);
         jButton4.setText("X");
          tabuleiro[3] ='X';
          this.jogar();
    }//GEN-LAST:event_escrever3

    private void escrever4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever4
        // TODO add your handling code here:
        // jButton5.setEnabled(false);
         jButton5.setText("X");
          tabuleiro[4] ='X';
          this.jogar();
    }//GEN-LAST:event_escrever4

    private void escrever5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever5
        // TODO add your handling code here:
        // jButton6.setEnabled(false);
         jButton6.setText("X");
          tabuleiro[5] ='X';
          this.jogar();
    }//GEN-LAST:event_escrever5

    private void escrever6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever6
        // TODO add your handling code here:
       //  jButton7.setEnabled(false);
         jButton7.setText("X");
          tabuleiro[6] ='X';
          this.jogar();
    }//GEN-LAST:event_escrever6

    private void escrever7(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever7
        // TODO add your handling code here:
        // jButton8.setEnabled(false);
         jButton8.setText("X");
          tabuleiro[7] ='X';
          this.jogar();
    }//GEN-LAST:event_escrever7

    private void escrever8(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escrever8
        // TODO add your handling code here:
        // jButton9.setEnabled(false);
         jButton9.setText("X");
        tabuleiro[8] ='X';
        this.jogar();
    }//GEN-LAST:event_escrever8

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void Reiniciar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reiniciar
        // TODO add your handling code here:
       /* tabuleiro = preencher(tabuleiro);
          jButton1.setText("");
           jButton2.setText("");
            jButton3.setText("");
             jButton4.setText("");
              jButton5.setText("");
               jButton6.setText("");
                jButton7.setText("");
                 jButton8.setText("");
                  jButton9.setText(""); */
                  
                  String[] v = {"ola","mundo"};
                  main(v);
   
    }//GEN-LAST:event_Reiniciar

    private void terminar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminar
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_terminar

    private void bolaComecar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bolaComecar
        // TODO add your handling code here:
         jButton12.setVisible(false);
         jButton13.setVisible(false);
         jPanel1.setVisible(true);
        jogar();
        
    }//GEN-LAST:event_bolaComecar

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void comecarX(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comecarX
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_comecarX

    private void xComecar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xComecar
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
    }//GEN-LAST:event_xComecar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         tabuleiro = preencher(tabuleiro);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }
    
    private static char[] preencher(char v[]){
        for ( int i=0; i<v.length; i++) {
             v[i] = '_'; 
         }
        return v;
    }

    
    private static char[] tabuleiro = new char[9] ;
     Query consultQuery = new Query("consult('src/jogodavelha/jogo.pl')");
     boolean consultSuccess = consultQuery.hasSolution(); 
    
    private void jogar (){
        String tab = vetorParaString(tabuleiro);
        int jogada;
        
            
        if (consultSuccess) {
            
           Query consVitoria = new Query("vitoria(Jogador, [" +tab +"])");
            Map<String, Term> res = consVitoria.oneSolution();
            String vitoria = "";
            
            if(res != null){
            vitoria = res.get("Jogador").toString().trim();
            }
               
           if(vitoria.equals("'X'") || vitoria.equals("'O'")) {
               
              
                Object[] options = { "Voltar" };
                     int choice = JOptionPane.showOptionDialog(null,vitoria +" VENCEU O JOGO" , "Estado Final",
                     JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

                        if (choice == 0) {
                             // System.exit(0);
                           /* tabuleiro = preencher(tabuleiro);
                                jButton1.setText("");
                                 jButton2.setText("");
                                  jButton3.setText("");
                                   jButton4.setText("");
                                    jButton5.setText("");
                                     jButton6.setText("");
                                      jButton7.setText("");
                                       jButton8.setText("");
                                        jButton9.setText("");*/
                            String[] v = {"ola","mundo"};
                            main(v);
                        }
           }
           
           
           else{
               
            Query jogadas = new Query("melhor_jogada('O', [" +tab +"], P)");
                Map<String, Term> resposta = jogadas.oneSolution();
              
              jogada= 9;  
             if(resposta!=null){
             jogada = resposta.get("P").intValue();
             }else{
                 
                    Object[] options = { "Voltar" };
                     int choice = JOptionPane.showOptionDialog(null, "EMPATE", "Estado Final",
                     JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

                        if (choice == 0) {
                             // System.exit(0);
                           /* tabuleiro = preencher(tabuleiro);
                                jButton1.setText("");
                                 jButton2.setText("");
                                  jButton3.setText("");
                                   jButton4.setText("");
                                    jButton5.setText("");
                                     jButton6.setText("");
                                      jButton7.setText("");
                                       jButton8.setText("");
                                        jButton9.setText(""); */
                           String[] v = {"ola","mundo"};
                            main(v);
                           
                        }
                 
             }
             tabuleiro[jogada]='O';
             tab = vetorParaString(tabuleiro);
             switch(jogada){
                 case 0 -> {
                     jButton1.setText("O");
                      //jButton1.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
                 case 1 -> {
                     jButton2.setText("O");
                      //jButton2.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
                 case 2 -> {
                     jButton3.setText("O");
                      //jButton3.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
                 case 3 -> {
                     jButton4.setText("O");
                     // jButton4.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
                 case 4 -> {
                     jButton5.setText("O");
                     // jButton5.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
                 case 5 -> {
                     jButton6.setText("O");
                     // jButton6.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
                 case 6 -> {
                     jButton7.setText("O");
                     // jButton7.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
                 case 7 -> {
                     jButton8.setText("O");
                     // jButton8.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
                 case 8 -> {
                     jButton9.setText("O");
                      //jButton9.setEnabled(false);
                      analisarVitoria(tab, jogada);
                      analisarEmpate(tab, jogada);
                 }
             }
           }
         
        } else {
            System.out.println("Falha ao consultar o arquivo Prolog.");
        }
        
    }
    
     private static String vetorParaString(char[] vetor) {
        StringBuilder resultado = new StringBuilder();
        for (char elemento : vetor) {
              resultado.append("'");
              resultado.append(elemento);
              resultado.append("',");
            
        }
         resultado.deleteCharAt(resultado.length() - 1);
        return resultado.toString();
    }
     private void analisarEmpate(String tab , int jogada){
         Query empate = new Query("jogo_terminou_empate([" +tab +"])");
                       
                 if(empate.hasSolution()){
                    Object[] options = { "Voltar" };
                     int choice = JOptionPane.showOptionDialog(null, "EMPATE", "Estado Final",
                     JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

                        if (choice == 0) {
                            
                           String[] v = {"ola","mundo"};
                            main(v);
                           
                        }
     }
     }
     private  void analisarVitoria( String tab , int j){
           Query consVitoria = new Query("vitoria(Jogador, [" +tab +"])");
            Map<String, Term> res = consVitoria.oneSolution();
            String vitoria = "";
            
            if(res != null){
            vitoria = res.get("Jogador").toString().trim();
            }
               
           if(vitoria.equals("'X'") || vitoria.equals("'O'")) {
               
               
                Object[] options = { "Voltar" };
                     int choice = JOptionPane.showOptionDialog(null,vitoria +" VENCEU O JOGO" , "Estado Final",
                     JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

                        if (choice == 0) {
                           // System.exit(0);
                           /* tabuleiro = preencher(tabuleiro);
                                jButton1.setText("");
                                 jButton2.setText("");
                                  jButton3.setText("");
                                   jButton4.setText("");
                                    jButton5.setText("");
                                     jButton6.setText("");
                                      jButton7.setText("");
                                       jButton8.setText("");
                                        jButton9.setText("");*/
                            String[] v = {"ola","mundo"};
                            main(v);
                        }
           }
         
     }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
